version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=192.168.1.10,192.168.1.11,192.168.2.62,127.0.0.1,localhost,sgportal,sgportal.smitelectra.nl,berkhout.ddns.net,jupiter
      - DEBUG=1

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
