version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./camera:/app
    command: sh -c "python manage.py runserver 0.0.0.0:9000"
    environment:
      - DEBUG=1
    network_mode: host
