version: '3.7'

services:
  app:
    build:
      context: .
    volumes: 
      - /home/jan/media/:/code/camera/media
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_CALLER_ID=${TWILIO_CALLER_ID} 
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - SESSION_COOKIE_AGE=${SESSION_COOKIE_AGE} 
    
    ports:
      - "8010:8010"
    command: sh -c "python manage.py runserver 0.0.0.0:8010"


   
   
