version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - /home/jan/media/:/code/camera/static/media
    environment:
      - DEBUG=1
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_CALLER_ID=+${TWILIO_CALLER_ID} 
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
   
   