version: '3.7'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - type: bind
        source: /mnt/cctv/KLANTEN/DOWNLOAD
        #source: /home/jan/videos
        target: /code/media
      - type: volume
        source: static_data
        target: /vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_CALLER_ID=${TWILIO_CALLER_ID} 
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      
      - SESSION_COOKIE_AGE=${SESSION_COOKIE_AGE} 
      
  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static_data:/vol/static
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    ports:
      - "9000:9000"
    depends_on:
      - app
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy

volumes:
  static_data:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
