# Generated by Django 3.1.3 on 2021-12-24 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrijf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('adres', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=6)),
                ('plaats', models.CharField(blank=True, max_length=50)),
                ('land', models.CharField(default='Nederland', max_length=50)),
                ('email', models.EmailField(default='info@bedrijf.nl', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('telefoon', models.CharField(blank=True, max_length=16)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'bedrijf',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('gps_locatie', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datum_geplaatst', models.DateTimeField(default=django.utils.timezone.now)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.bedrijf')),
            ],
            options={
                'verbose_name_plural': 'camera',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('naam', models.CharField(max_length=50)),
                ('email', models.EmailField(default='info@me.nl', max_length=254)),
                ('telefoon', models.CharField(default='06 11 22 33 44', max_length=16)),
                ('soort', models.IntegerField(choices=[(0, 'Amdin'), (1, 'Contact'), (2, 'Wijkbeheerder')], default=0)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'gebruiker',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Wijk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('plaats', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.bedrijf')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.gebruiker')),
            ],
            options={
                'verbose_name_plural': 'wijk',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, unique=True)),
                ('opname_van', models.DateTimeField(default=django.utils.timezone.now)),
                ('opname_tot', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_link', models.URLField(blank=True, max_length=500)),
                ('codec', models.CharField(blank=True, max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
            options={
                'verbose_name_plural': 'video',
                'ordering': ['naam'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='wijk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.wijk'),
        ),
        migrations.AddField(
            model_name='bedrijf',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.gebruiker'),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('naam', 'bedrijf', 'wijk')},
        ),
    ]
