# Generated by Django 4.1.2 on 2023-02-17 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('straat', models.CharField(default='Straatnaam 1', max_length=50)),
                ('postcode', models.CharField(default='0000AA', max_length=6)),
                ('plaats', models.CharField(default='Plaats', max_length=50)),
                ('land', models.CharField(default='Nederland', max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'adress',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Bedrijf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('email', models.EmailField(default='info@bedrijf.nl', max_length=254)),
                ('website', models.URLField(blank=True, default='www.bedrijf.nl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('telefoon', models.CharField(blank=True, default='000 1234567', max_length=16)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.adress')),
            ],
            options={
                'verbose_name_plural': 'bedrijf',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('plaats', models.CharField(blank=True, max_length=50)),
                ('gps_locatie', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datum_geplaatst', models.DateTimeField(default=django.utils.timezone.now)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'camera',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Gebied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('memo', models.TextField(blank=True)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'authorisatie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('naam', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='info2@me.nl', max_length=254)),
                ('telefoon', models.CharField(default='06 11 22 33 44', max_length=16)),
                ('soort', models.IntegerField(choices=[(0, 'Admin'), (1, 'Contact'), (2, 'Wijkbeheerder')], default=1)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'gebruiker',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.adress')),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.bedrijf')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.gebruiker')),
            ],
            options={
                'verbose_name_plural': 'locatie',
                'ordering': ['naam'],
                'unique_together': {('naam', 'adres')},
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernr', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(default='empty', max_length=500)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'log',
                'ordering': ['ordernr'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoPath', models.CharField(max_length=100)),
                ('maximumConvert', models.IntegerField(default=3, max_length=2)),
                ('conversion_running', models.BooleanField(default=False)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'parameter',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('ordernr', models.CharField(default='', max_length=50)),
                ('opname_van', models.DateTimeField(default=django.utils.timezone.now)),
                ('opname_tot', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_link', models.CharField(blank=True, max_length=500)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('codec', models.CharField(blank=True, default='vb9', max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
            options={
                'verbose_name_plural': 'video',
                'ordering': ['ordernr', 'naam', 'camera', 'codec'],
                'unique_together': {('naam', 'camera')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernr', models.CharField(default='', max_length=50)),
                ('keep_original', models.BooleanField(default=False)),
                ('auto_cleanup', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.bedrijf')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.gebruiker')),
            ],
            options={
                'verbose_name_plural': 'ServiceOrder',
                'ordering': ['ordernr'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.locatie'),
        ),
        migrations.CreateModel(
            name='Authorisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.bedrijf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.gebruiker')),
            ],
        ),
        migrations.CreateModel(
            name='Opname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('datum_aangevraagd', models.DateTimeField(default=django.utils.timezone.now)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.locatie')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.video')),
            ],
            options={
                'verbose_name_plural': 'opname',
                'ordering': ['naam'],
                'unique_together': {('naam', 'locatie')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('naam', 'locatie')},
        ),
    ]
