# Generated by Django 3.1.3 on 2021-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='locatie',
            field=models.CharField(default='locatie', max_length=50),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='soort',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Contact'), (2, 'Wijkbeheerder')], default=0),
        ),
    ]
