# Generated by Django 3.1.3 on 2021-12-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20211224_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
