# Generated by Django 3.1.3 on 2022-01-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20211227_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['naam', 'codec'], 'verbose_name_plural': 'video'},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('naam', 'codec')},
        ),
    ]
